In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
# Read the data
piezo = pd.read_csv('piezo.csv')
piezo

,mID,formula,vm1,vm2,vm3,sites,pointGroup,spaceGroup,volume,a,...,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18
0,mp-22925,AgI,1.00000,1.00000,1.00000,2,-43m,216,73.219583,4.695849,...,0.00000,0.00000,-0.158420,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,-0.158420
1,mp-406,CdTe,1.00000,1.00000,1.00000,2,-43m,216,72.827208,4.687445,...,0.00000,0.00000,0.008397,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.008397
2,mp-1639,BN,1.00000,1.00000,1.00000,2,-43m,216,11.917209,2.563873,...,0.00000,0.00000,0.896760,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.896760
3,mp-10695,ZnS,1.00000,1.00000,1.00000,2,-43m,216,40.475675,3.853923,...,0.00000,0.00000,0.053160,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.053160
4,mp-2176,ZnTe,1.00000,1.00000,1.00000,2,-43m,216,59.145615,4.373333,...,0.00000,0.00000,0.119310,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.119310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936,mp-705676,K4MoO8,0.50000,1.00000,-3.50000,13,1,1,258.802053,6.341684,...,0.68046,-0.65399,-0.317770,0.33611,-0.38481,0.10201,-1.28155,0.31958,-0.13885,-0.184660
937,mp-763696,Li5(CoO3)2,1.00000,-2.33333,-0.33333,13,1,1,145.770644,5.439459,...,-0.15267,-0.03830,-0.109820,-0.05374,0.32089,0.02941,-0.06276,-0.02598,0.01375,-0.050300
938,mp-767108,LiMn2(PO4)2,0.71429,-0.28571,1.00000,13,1,1,171.143703,4.579467,...,0.37914,-0.23421,-0.408210,0.20121,-0.15221,-0.31793,-0.11145,0.03585,-0.64307,0.105350
939,mp-767263,LiFe2(PO4)2,1.00000,0.00000,-0.71429,13,1,1,172.634994,4.551175,...,0.13472,-0.24265,-0.018610,0.18241,-0.05212,-0.00986,-0.06065,0.09324,-0.46343,0.012800
940,mp-767274,Li3MnSi2O7,0.66667,0.66667,1.00000,13,1,1,149.498912,4.665344,...,-0.68912,0.09022,-0.690080,0.03036,-0.18851,0.08265,-0.17635,-0.08920,-0.44677,-0.150750

In [10]:
#Call predictor variables and rows as capital X. Might not be feasible here.
X = piezo.iloc[:,0:5]

#Get all the rows and columns total, save to y. Testing specific column here.
y = piezo.loc[:,"volume"]

#The import function comes into play here
#For the Test set:
#This line pass in the dataframe with all the predictor variables (X), then the outcome variables (y), then the percentage size
train_test_split(X,y,test_size=.2)

[           mID     formula  vm1      vm2      vm3
 312   mp-10614       SrLiP  0.0  1.00000  0.00000
 693    mp-7670       K2Se3  1.0  0.00000  1.00000
 812  mp-673245         CuI  1.0  0.00000 -0.66667
 294   mp-23485     Ag2HgI4  1.0 -0.71429  0.85714
 297   mp-21374  Cd(InTe2)2  1.0  0.60000  0.80000
 ..         ...         ...  ...      ...      ...
 625  mp-542980       FeHO2  0.0  0.00000  1.00000
 409   mp-39542   KRb2ZrOF5  1.0  0.57143  0.71429
 11    mp-24864         CoO  1.0  1.00000  1.00000
 795    mp-7456        SnF2  1.0  1.00000  1.00000
 211    mp-9490    KAg2SbS4  1.0  1.00000  1.00000

 [752 rows x 5 columns],
            mID     formula  vm1  vm2      vm3
 688    mp-7446       Rb2S3  0.0  0.0  1.00000
 584  mp-556120  RbTl(SO4)2  1.0  0.0  0.00000
 309   mp-10161       KZnSb  0.0  1.0  0.00000
 794  mp-561224        TeO2  1.0  1.0  1.00000
 865  mp-759568    LiBiP2O7  1.0  1.0 -0.40000
 ..         ...         ...  ...  ...      ...
 739  mp-753539        SbOF  0.0  0.0  1.00000
 399  mp-560588         ZnS  0.0  0.0  1.00000
 292   mp-29403      GaCuI4  1.0 -0.4  0.80000
 52    mp-31451      ZrCoBi  1.0  1.0  1.00000
 728  mp-753378      TaGaO4  1.0  0.0  0.71429

 [189 rows x 5 columns],
 312     68.040336
 693    320.110778
 812    222.987317
 294    281.162298
 297    261.197814
           ...
 625     69.207393
 409    202.486630
 11      24.816670
 795    231.678364
 211    213.800744
 Name: volume, Length: 752, dtype: float64,
 688    321.527914
 584    191.474423
 309     98.439567
 794    188.779158
 865    146.329622
           ...
 739    242.275998
 399     81.074321
 292    242.607028
 52      60.651247
 728    132.184554
 Name: volume, Length: 189, dtype: float64]

In [11]:
#Save the outputs. As shown above, we recieve the training datasets first followed by the testing datasets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2)

#Seed will give you the same split every time
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2, random_state = 1337)